#!/usr/bin/env python
# coding: utf-8

# In[6]:


# -*- coding: utf-8 -*-
"""
#Lab 3
Generated by ArcGIS ModelBuilder on : 2023-02-08 21:31:49
"""
# Question 1 and 2 are in the MS document named lab3

import arcpy

# To allow overwriting outputs change overwriteOutput option to True.
arcpy.env.overwriteOutput = True
arcpy.env.workspace = 'C:\\Users\\akunna1\\Desktop\\GEOG 592\\Lab_3\\Lab_3_Akunna\\'

# Question 3
#Section for configuring input data sources
CITIES = "CITIES.shp"
intrstat = "intrstat.shp"

# Get user's input for two highway choices
hwyListStr = input('Please type two highways to analyze- ExL I40 I80\n')
hwyList = hwyListStr.split()
hw1 = hwyList[0]
bufDistStr = input('Please input the buffer distance values here (in miles): Ex - 30\n')

for aHwy in hwyList:
    # Process: Select (Select) (analysis)
    intrstat_Select_2_4 = "intrstat_Select.shp"
    arcpy.analysis.Select(intrstat, intrstat_Select_2_4, "ROUTE_NUM = '"+aHwy+"'")

    # Process: Buffer (Buffer) (analysis)
    intrstat_Buffer_4 = "intrstat_Buffer_4.shp"
    arcpy.analysis.Buffer(intrstat_Select_2_4, intrstat_Buffer_4, bufDistStr+" Miles", "FULL", "ROUND", "NONE", [], "PLANAR")

    # Process: Clip (Clip) (analysis)
    CITIES_Clip_4 = "CITIES_Clip_4.shp"
    arcpy.analysis.Clip(CITIES, intrstat_Buffer_4, CITIES_Clip_4)

    # Process: Summary Statistics (Summary Statistics) (analysis)
    Sum_table_2_4 = "Cities"+aHwy+'Buffer'+bufDistStr+".dbf"
    arcpy.analysis.Statistics(CITIES_Clip_4, Sum_table_2_4, [["POP1990", "SUM"], ["HISPANIC", "SUM"]])
    
    print(aHwy+ ' just being completed.')
print(' All Completed')


# Question 4
orange_durham = "orange_durham.shp"
CITIES_q4 = "CITIES.shp"

# Process: Clip (Clip) (analysis)
CITIES_Clip_q4 = "cities_clip.shp" # creating a new shape file
arcpy.analysis.Clip(CITIES_q4, orange_durham, CITIES_Clip_q4)

# Process: Buffer (Buffer) (analysis)
cities_Buffer = "cities_buf.shp" # creating a new shape file
arcpy.analysis.Buffer(CITIES_Clip_q4, cities_Buffer, "3 Miles", "FULL", "ROUND", "NONE", [], "PLANAR")

#Deleting the clipped result
arcpy.Delete_management(CITIES_Clip_q4)


#question 5
CITIES_q5 = "CITIES.shp"

# Process: Select (Select) (analysis)
cities_select_q5 = "cities_250000.shp" # creating a new shape file
arcpy.analysis.Select(CITIES_q5, cities_select_q5, "POP1990 > 250000")


# In[ ]:




